### ISSUE TITLE
the output log does not display any useful information for failed jobs

### ISSUE THREAD

**Issue by smilesun** [jdblischak/smk-simple-slurm#14]
is there a way to specify error logs as well?

**Comment by jdblischak** [comment]
@smilesun By default this profile has Slurm write both stdout and stderr to the same log file. This is because only `--output` is defined and not `--error`

https://github.com/jdblischak/smk-simple-slurm/blob/2df811f8a4b3eae95dae13272094cb4648a7198b/simple/config.yaml#L9

You can update the `sbatch` command to write stdout and stderr to separate files by also defining `--error`, which I've demonstrated in the example [`separate-stderr`](https://github.com/jdblischak/smk-simple-slurm/tree/main/examples/separate-stderr)

However, I'm not sure how much this will help you in practice. If there is nothing informative in the combined file, it's unlikely separating them will help much (unless the combined file is very cluttered). The messages written to stderr are determined by the bioinformatics tool you are using. Either it doesn't provide informative messages, or it is being killed by the scheduler (eg if it runs out of memory or time before it can write to stderr). You can check the status of the failed job with `sacct -j <jobid>`
