### ISSUE TITLE
add to Snakemake-Profiles project?

### ISSUE THREAD

**Issue by mufernando** [jdblischak/smk-simple-slurm#4]
Hi, this is great! Thank you!

Are you thinking about adding this to the Snakemake-Profiles project? It would be great so that this repo is more broadly distributed/easily found.

https://github.com/snakemake-profiles/doc

**Comment by jdblischak** [comment]
> Hi, this is great! Thank you!

@mufernando Thanks for the positive feedback! I'm glad you find it useful.

> Are you thinking about adding this to the Snakemake-Profiles project? 

I wish I could, but I don't think it would be accepted. My repo doesn't follow the [required guidelines](https://github.com/snakemake-profiles/doc#guidelines). Most notably it isn't installable via cookiecutter. However, it also doesn't follow the typical style of having multiple Python scripts to handle job submission, etc.

And I don't want to change it, since I this the simplicity is its strength. It's easier to customize and quicker to execute.

> It would be great so that this repo is more broadly distributed/easily found.

I'm interested in distributing this as widely as possible. Please share with your colleagues, and let me know if there are other avenues for letting Snakemake users know about this profile. Thanks!

**Comment by jdblischak** [comment]
The maintainer of the official Slurm profile has graciously added a new section to the REAMDE that mentions smk-simple-slurm. Now any Snakemake user investigating how to execute their pipeline on Slurm will be notified that this alternative exists.

https://github.com/Snakemake-Profiles/slurm#alternatives
https://github.com/Snakemake-Profiles/slurm/pull/84

**Comment by jdblischak** [comment]
@boulund Thanks so much for the positive feedback!
